-- Tables, types and indexes for the sample store.
--
-- Applied by `twitch-metrics db --init`, which runs each numbered file in this
-- directory once, in one transaction, and records it in schema_version.
-- Everything here is written to be re-runnable: applying it twice is a no-op,
-- so a half-finished --init can simply be run again.
--
-- The shape follows one rule that is worth stating before the first table.
-- Every aggregate in this project buckets by LOCAL date -- chart.select_day(),
-- chart.days_present() and trends._live_on() all decide what day a sample
-- belongs to with `when.astimezone().date()`. PostgreSQL cannot index that:
-- `timezone(text, timestamptz)` is STABLE rather than IMMUTABLE, so neither an
-- expression index nor a GENERATED ... STORED column on a local date is legal.
--
-- So no sample row stores a local date. The report functions convert their
-- PARAMETERS once, into a half-open range of instants, and every scan is then
-- an ordinary btree range on sampled_at:
--
--     v_from := (p_from::timestamp)       AT TIME ZONE v_tz;
--     v_to   := ((p_to + 1)::timestamp)   AT TIME ZONE v_tz;
--     ... WHERE sampled_at >= v_from AND sampled_at < v_to
--
-- That also gets DST right for nothing: a 23- or 25-hour local day is simply a
-- narrower or wider range of instants. A local date is stored only in the
-- report tables, where it is a label on a computed result and sits next to the
-- timezone that produced it.

CREATE SCHEMA IF NOT EXISTS tm;
SET LOCAL search_path = tm, public;


-- --------------------------------------------------------------------------
-- types
-- --------------------------------------------------------------------------

-- An enum rather than a lookup table: four bytes, it sorts, it lets the
-- planner discard a branch of the sample_all view when a caller says
-- `WHERE platform = 'twitch'`, and adding a third platform is one ALTER TYPE
-- rather than a migration. DO blocks because CREATE TYPE has no IF NOT EXISTS.
DO $$ BEGIN
    CREATE TYPE tm.platform_kind AS ENUM ('twitch', 'youtube');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- daily.classify_day() already draws this distinction and the site depends on
-- it: 'dark' is polled-and-offline (a day off, which renders as a dash) and
-- 'silent' is never-polled, which on today means the poller is dead and fails
-- the run. Collapsing them would make a dead poller invisible.
DO $$ BEGIN
    CREATE TYPE tm.day_status AS ENUM ('live', 'dark', 'silent');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Why a broadcast stopped being the live one. 'offline' is a clean end,
-- 'superseded' is youtube.pick_live()'s two-at-once case, and 'stale' is a
-- guess made by close_stale_streams() after a poller died -- worth keeping
-- apart, because a duration derived from a guess should be readable as one.
DO $$ BEGIN
    CREATE TYPE tm.stream_end AS ENUM ('offline', 'superseded', 'stale', 'manual');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Exactly the keys of chart.METRICS, so adding a metric to a chart is an
-- ALTER TYPE and not a new column on the report table.
DO $$ BEGIN
    CREATE TYPE tm.metric_kind AS ENUM
        ('viewers', 'chatters', 'followers', 'subscribers', 'likes');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;


-- --------------------------------------------------------------------------
-- identity
-- --------------------------------------------------------------------------

-- The creator, and the thing the website is named after. One row per slug.
--
-- The SLUG is the key, not the login: config.channel_slug() lowercases, so the
-- CSVs have always collapsed IGN and ign into one file, and daily._accept()
-- already de-duplicates the report's channel list by slug. Keying on the raw
-- login here would quietly make them two channels -- and then `daily` would
-- report one and chart the other.
CREATE TABLE IF NOT EXISTS tm.channel (
    channel_id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug             text        NOT NULL UNIQUE,
    display_name     text        NOT NULL,
    -- The zone this channel's reports call a day. Stored per channel rather
    -- than per server so moving the box cannot silently redraw history.
    -- Validated by upsert_channel(), not by a CHECK: verifying a zone needs
    -- AT TIME ZONE, which is STABLE, and a CHECK constraint may only call
    -- IMMUTABLE functions.
    report_timezone  text        NOT NULL DEFAULT 'UTC',
    created_at       timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT channel_slug_shape CHECK (slug ~ '^[a-z0-9_-]+$')
);

-- One row per channel per platform.
--
-- Not a set of nullable columns on channel(), for three reasons: .env already
-- notes that "a creator's handles on the two platforms need not match", so the
-- handle cannot live on the channel; the YouTube UC id and uploads playlist id
-- have nowhere else to go; and both pollers currently re-resolve that identity
-- from the API on every single restart (poll.py:187, youtube_cmd.py:173), which
-- this table turns into a SELECT.
CREATE TABLE IF NOT EXISTS tm.platform_account (
    account_id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id           bigint NOT NULL REFERENCES tm.channel ON DELETE RESTRICT,
    platform             tm.platform_kind NOT NULL,
    handle               text NOT NULL,   -- twitch login / youtube @handle, as configured
    platform_ref         text,            -- twitch broadcaster_id / youtube UC... id
    uploads_playlist_id  text,            -- youtube only
    platform_title       text,            -- channels.list snippet.title
    enabled              boolean NOT NULL DEFAULT true,
    resolved_at          timestamptz,
    CONSTRAINT platform_account_one_per_platform UNIQUE (channel_id, platform),
    CONSTRAINT platform_account_handle_key       UNIQUE (platform, handle),
    -- Carries the composite foreign key on the sample tables; see there.
    CONSTRAINT platform_account_channel_key      UNIQUE (account_id, channel_id),
    CONSTRAINT platform_account_playlist_shape
        CHECK (platform <> 'twitch' OR uploads_playlist_id IS NULL),
    -- youtube.CHANNEL_ID_RE, moved into the schema.
    CONSTRAINT platform_account_ref_shape CHECK (
        platform <> 'youtube' OR platform_ref IS NULL
        OR platform_ref ~ '^UC[A-Za-z0-9_-]{22}$')
);


-- --------------------------------------------------------------------------
-- broadcasts
-- --------------------------------------------------------------------------

-- One row per broadcast. title, game and started_at were copied onto all 353
-- rows of a single stream in the CSV; here they are stored once.
--
-- Verified against every CSV in data/ and tests/fixtures/: started_at is 1:1
-- with the platform's stream id, and no title ever changed mid-broadcast -- so
-- holding the last-observed title on this row is lossless today. If churn ever
-- appears, day_title()'s "last one wins" rule is already what an UPDATE gives.
CREATE TABLE IF NOT EXISTS tm.stream (
    stream_id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id          bigint NOT NULL REFERENCES tm.platform_account ON DELETE RESTRICT,
    platform_stream_id  text NOT NULL,   -- twitch stream id / youtube video id
    title               text,
    game                text,            -- twitch only: YouTube has no category
    started_at          timestamptz,
    first_sample_at     timestamptz(0) NOT NULL,
    last_sample_at      timestamptz(0) NOT NULL,
    sample_count        integer NOT NULL DEFAULT 0,
    -- NULL means "live right now", which is what makes this table the lookup
    -- cache as well as the identity table. Anchored to the last LIVE sample
    -- rather than the offline one that revealed the end, so a broadcast's
    -- duration does not depend on the poll interval.
    ended_at            timestamptz(0),
    ended_reason        tm.stream_end,
    -- Consecutive polls that failed to see this stream live. Closing on the
    -- first miss would be wrong: videos.list reports liveBroadcastContent
    -- 'none' for a beat mid-stream, and evicting the cache over that sends the
    -- next poll back to the two-unit playlist walk -- spending quota to punish
    -- a transient.
    miss_streak         smallint NOT NULL DEFAULT 0,
    CONSTRAINT stream_natural_key UNIQUE (account_id, platform_stream_id),
    CONSTRAINT stream_ended_pair  CHECK ((ended_at IS NULL) = (ended_reason IS NULL)),
    CONSTRAINT stream_ordered     CHECK (last_sample_at >= first_sample_at)
);

-- THE live-lookup cache, and the reason it needs no table of its own: "which
-- broadcast is open" is a property of the broadcast. A partial unique index
-- answers it in one index probe -- which is the point, since the poller asks
-- before deciding whether to spend one quota unit or two -- and makes "two
-- open streams for one account" unrepresentable rather than merely unlikely.
CREATE UNIQUE INDEX IF NOT EXISTS stream_open_one_per_account
    ON tm.stream (account_id) WHERE ended_at IS NULL;

-- Listing a channel's broadcasts newest first.
CREATE INDEX IF NOT EXISTS stream_account_started
    ON tm.stream (account_id, started_at DESC NULLS LAST);


-- --------------------------------------------------------------------------
-- samples
-- --------------------------------------------------------------------------

-- Two tables rather than one, because the metrics genuinely differ: a YouTube
-- sample CANNOT have a chat size (totalChatCount needs OAuth as the channel's
-- own account, so an API key cannot reach it) and a Twitch sample cannot have a
-- like count. A column that does not exist is a stronger and more readable
-- statement than a CHECK constraint saying it must be NULL.
--
-- The legacy viewers_*.csv format gets no table of its own: METRICS is a strict
-- superset of VIEWERS and there is no timestamp overlap between the two files
-- for the same channel, so those rows land here with the two extra columns NULL
-- and ingest_source recording where they came from. storage._widen() disappears
-- with them -- adding a column to a table is not a whole-file rewrite.
CREATE TABLE IF NOT EXISTS tm.twitch_sample (
    sample_id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id      bigint NOT NULL,
    account_id      bigint NOT NULL,
    -- Second precision, because that is all storage.utc_stamp() ever wrote
    -- ("%Y-%m-%dT%H:%M:%SZ"). Making the column match means the unique
    -- constraint below means exactly what the CSV meant, and a stray
    -- microsecond cannot create a phantom second sample for the same tick.
    sampled_at      timestamptz(0) NOT NULL,
    -- NULL is offline. Verified across all 12 CSVs: every live row carries a
    -- stream id and no offline row does, so this column IS the liveness flag
    -- and there is no separate is_live to contradict it.
    stream_id       bigint REFERENCES tm.stream ON DELETE RESTRICT,
    viewer_count    integer,
    -- Recorded while the channel is dark too, deliberately: a follower count
    -- keeps moving when nobody is streaming, and the daily delta would lose
    -- every follower gained on a day off if these were live-only.
    follower_count  integer,
    chatter_count   integer,
    -- 'poller', 'metrics_csv', 'viewers_csv', 'spool'. Provenance without a
    -- second table, which is what lets the legacy format merge in cleanly.
    ingest_source   text NOT NULL DEFAULT 'poller',

    -- The invariant made structural instead of merely observed -- and unlike a
    -- local date this one is IMMUTABLE, so it can be indexed.
    is_live boolean GENERATED ALWAYS AS (stream_id IS NOT NULL) STORED,

    -- channel_id is denormalised, and the composite FK is what stops it
    -- drifting: it can only hold a channel that really owns this account. It is
    -- load-bearing rather than a convenience, because an offline row has no
    -- stream -- so without it, an offline sample would have no path to a
    -- channel at all, and "was this channel dark or unpolled?" would be
    -- unanswerable.
    CONSTRAINT twitch_sample_account_fk FOREIGN KEY (account_id, channel_id)
        REFERENCES tm.platform_account (account_id, channel_id) ON DELETE RESTRICT,

    -- What makes the outage backfill idempotent: replaying a spooled row the
    -- database already has is ON CONFLICT DO NOTHING rather than a duplicate,
    -- so the replay watermark can overlap harmlessly. It also collapses the one
    -- genuinely duplicated timestamp in the archive (viewers_ign.csv holds
    -- 2026-08-21T17:09:52Z twice).
    CONSTRAINT twitch_sample_once UNIQUE (account_id, sampled_at),
    CONSTRAINT twitch_sample_viewers_live
        CHECK (viewer_count IS NULL OR stream_id IS NOT NULL),
    CONSTRAINT twitch_sample_nonneg CHECK (
        coalesce(viewer_count, 0) >= 0 AND coalesce(follower_count, 0) >= 0
        AND coalesce(chatter_count, 0) >= 0)
);

CREATE TABLE IF NOT EXISTS tm.youtube_sample (
    sample_id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id        bigint NOT NULL,
    account_id        bigint NOT NULL,
    sampled_at        timestamptz(0) NOT NULL,
    stream_id         bigint REFERENCES tm.stream ON DELETE RESTRICT,
    -- Nullable on a LIVE row on purpose, unlike Twitch: YouTube omits
    -- concurrentViewers for the first moments of a broadcast and whenever the
    -- owner has hidden it, so a live video with no number is normal.
    viewer_count      integer,
    -- Rounded by YouTube to three significant figures, so it steps rather than
    -- climbs. The chart is not broken.
    subscriber_count  integer,
    like_count        integer,
    ingest_source     text NOT NULL DEFAULT 'poller',
    is_live boolean GENERATED ALWAYS AS (stream_id IS NOT NULL) STORED,
    CONSTRAINT youtube_sample_account_fk FOREIGN KEY (account_id, channel_id)
        REFERENCES tm.platform_account (account_id, channel_id) ON DELETE RESTRICT,
    CONSTRAINT youtube_sample_once UNIQUE (account_id, sampled_at),
    CONSTRAINT youtube_sample_viewers_live
        CHECK (viewer_count IS NULL OR stream_id IS NOT NULL),
    CONSTRAINT youtube_sample_nonneg CHECK (
        coalesce(viewer_count, 0) >= 0 AND coalesce(subscriber_count, 0) >= 0
        AND coalesce(like_count, 0) >= 0)
);

-- Per-broadcast reads: chart.series_of() and chart.summarise() walk one session
-- in timestamp order. Partial, because offline rows have no stream_id and are
-- most of the table for a channel that streams a few hours a day -- on the
-- largest archive here, 2,388 of 2,741 Twitch rows are offline.
CREATE INDEX IF NOT EXISTS twitch_sample_stream
    ON tm.twitch_sample (stream_id, sampled_at) WHERE stream_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS youtube_sample_stream
    ON tm.youtube_sample (stream_id, sampled_at) WHERE stream_id IS NOT NULL;

-- Deliberately NOT created here:
--
--   * an index on (account_id, sampled_at). The UNIQUE constraint above
--     already is one, and every report refresh is "one account, one range of
--     instants", so a second copy would be pure write cost.
--   * a covering index WHERE viewer_count IS NOT NULL. It would earn nothing on
--     3,200 rows; revisit past roughly a million, which a 60-second poller
--     reaches in about a year per account.
--   * anything on channel_id alone. The only channel-wide query is the
--     cross-platform minute grid, and that goes through sample_all, which
--     resolves to a per-account scan on each branch anyway.


-- One read surface over the two tables, so every report function is written
-- once instead of twice. The platform is a constant in each branch, which lets
-- the planner discard a branch entirely when a caller says
-- `WHERE platform = 'twitch'` -- so this costs nothing over touching the table
-- directly. Writes never come through here; they go through record_*_sample().
CREATE OR REPLACE VIEW tm.sample_all AS
    SELECT channel_id, account_id, 'twitch'::tm.platform_kind AS platform,
           sampled_at, stream_id, is_live, viewer_count,
           follower_count, chatter_count,
           NULL::integer AS subscriber_count, NULL::integer AS like_count,
           ingest_source
      FROM tm.twitch_sample
    UNION ALL
    SELECT channel_id, account_id, 'youtube'::tm.platform_kind,
           sampled_at, stream_id, is_live, viewer_count,
           NULL::integer, NULL::integer,
           subscriber_count, like_count,
           ingest_source
      FROM tm.youtube_sample;


-- --------------------------------------------------------------------------
-- report tables
-- --------------------------------------------------------------------------
--
-- Filled by the refresh_* functions in 003_reports.sql, never written directly.
-- The timezone is part of every key rather than an assumption, so recomputing a
-- trend under a different zone adds rows instead of destroying the old ones.

-- trends.daily_peaks(), plus daily.day_title(). One row for EVERY day in a
-- refreshed range, including the ones with no stream, because "did not stream"
-- is a fact the site has to render (as a dash) and not an absence.
CREATE TABLE IF NOT EXISTS tm.report_daily_peak (
    channel_id  bigint NOT NULL REFERENCES tm.channel ON DELETE CASCADE,
    tz          text NOT NULL,
    local_date  date NOT NULL,
    platform    tm.platform_kind NOT NULL,
    status      tm.day_status NOT NULL,
    -- NULL on a day with no live samples, and NEVER 0. The distinction is the
    -- whole point: the channel was not streaming, which is a different
    -- statement from "nobody watched", and drawing them alike would invent a
    -- catastrophic day out of a day off.
    peak_viewers        integer,
    peak_at             timestamptz(0),
    -- Six decimal places, not three. These are means, and
    -- _busiest_window() picks an argmax over SUMS of them -- so
    -- rounding that is invisible in a bar's height can still break a
    -- tie differently from Python and move the whole 12-hour window.
    -- The extra digits cost nothing and make the parity test exact.
    avg_viewers         numeric(18,6),
    low_viewers         integer,
    sample_count        integer NOT NULL,
    live_sample_count   integer NOT NULL,
    viewer_sample_count integer NOT NULL,
    first_live_at       timestamptz(0),
    last_live_at        timestamptz(0),
    title               text,   -- the day's last non-empty title
    -- Spanning the whole day, live rows and dark ones alike: the charts show
    -- these as a delta (last - first) rather than a peak, and a follower count
    -- keeps moving while the channel is offline.
    follower_first   integer,
    follower_last    integer,
    subscriber_first integer,
    subscriber_last  integer,
    follower_delta   integer GENERATED ALWAYS AS (follower_last - follower_first) STORED,
    subscriber_delta integer GENERATED ALWAYS AS (subscriber_last - subscriber_first) STORED,
    computed_at      timestamptz NOT NULL DEFAULT now(),
    -- Column order is the read plan: (channel_id, tz, local_date) as a prefix
    -- lets the site pull a date range covering BOTH platforms in one index
    -- scan, which is exactly how daily.report_channel() iterates. Putting
    -- platform third would split that into two scans.
    PRIMARY KEY (channel_id, tz, local_date, platform),
    -- trends.daily_peaks()' load-bearing invariant, promoted from a docstring
    -- to a constraint: a future refresh that writes 0 for a day off now aborts
    -- instead of quietly inventing a disaster.
    CONSTRAINT report_daily_peak_dark_is_null
        CHECK (status = 'live' OR (peak_viewers IS NULL AND peak_at IS NULL)),
    CONSTRAINT report_daily_peak_peak_pair
        CHECK ((peak_viewers IS NULL) = (peak_at IS NULL))
);

-- trends.clock_buckets(). Slot 0 is local midnight.
--
-- SPARSE: only slots that actually had a live sample get a row, because that is
-- what the Python dict is and because trends.compare_slots() needs "the union
-- of slots any day used". Densifying to 48 rows a day would make every quiet
-- night read as an audience of zero.
CREATE TABLE IF NOT EXISTS tm.report_clock_bucket (
    channel_id     bigint NOT NULL REFERENCES tm.channel ON DELETE CASCADE,
    tz             text NOT NULL,
    -- In the key because `daily --bucket` is a CLI knob: two widths can coexist
    -- rather than one overwriting the other.
    bucket_minutes smallint NOT NULL,
    local_date     date NOT NULL,
    platform       tm.platform_kind NOT NULL,
    slot           smallint NOT NULL,
    avg_viewers    numeric(18,6) NOT NULL,
    peak_viewers   integer NOT NULL,
    sample_count   integer NOT NULL,
    computed_at    timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (channel_id, tz, bucket_minutes, local_date, platform, slot),
    CONSTRAINT report_clock_bucket_slot_range CHECK (slot >= 0 AND slot < 1440),
    CONSTRAINT report_clock_bucket_width CHECK (bucket_minutes BETWEEN 1 AND 1440)
);

-- Serves compare_slots()' weighting step -- sum(avg_viewers) grouped by slot
-- across a six-day window -- which wants slot-major access the primary key
-- cannot give.
CREATE INDEX IF NOT EXISTS report_clock_bucket_slot_weight
    ON tm.report_clock_bucket (channel_id, tz, bucket_minutes, platform, slot)
    INCLUDE (avg_viewers);

-- chart.summarise(), one row per broadcast per metric.
--
-- Long format rather than a column per metric, so adding one to chart.METRICS
-- is an ALTER TYPE on metric_kind rather than a migration here.
--
-- Keyed per BROADCAST, which is not the same as per session:
-- chart.split_sessions() also breaks on an offline row and on a sample gap
-- wider than median_step * 2.5, and drops any run of fewer than two samples --
-- so one stream becomes two sessions the first time a poller restarts
-- mid-broadcast. Sessions stay a read-time computation; this table does not
-- try to express them.
CREATE TABLE IF NOT EXISTS tm.report_stream_metric (
    stream_id    bigint NOT NULL REFERENCES tm.stream ON DELETE CASCADE,
    metric       tm.metric_kind NOT NULL,
    peak         integer NOT NULL,
    peak_at      timestamptz(0) NOT NULL,
    -- Seconds from the broadcast's first sample. chart.py's x axis is elapsed
    -- time, not clock time, so storing the clock alone would mean recomputing
    -- this on every read.
    peak_elapsed integer NOT NULL,
    low          integer NOT NULL,
    avg          numeric(18,6) NOT NULL,
    first_value  integer NOT NULL,
    last_value   integer NOT NULL,
    n            integer NOT NULL,
    -- What the charts actually print for followers and subscribers.
    delta        integer GENERATED ALWAYS AS (last_value - first_value) STORED,
    computed_at  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (stream_id, metric)
);
