-- Per-broadcast trends: followers gained, likes peaked, and where it happened.
--
-- The charts above these compare DATES that streamed (trends.streamed_window()).
-- That axis cannot answer "which park" -- a Sunday spent at EPCOT and then at
-- Animal Kingdom is two answers, and a date-major axis has room for one. So this
-- file adds an axis of BROADCASTS, one row per tm.stream.
--
-- Almost nothing here is new arithmetic. tm.report_stream_metric has held the
-- per-broadcast follower delta and like peak since 001, and 006 finally made the
-- function that fills it work. What was missing was a row a chart can read in one
-- go: the platform, the local date, the weekday, and the location, next to the two
-- numbers. That is tm.report_stream_trend.
--
-- The rollups by weekday and by location are READ functions rather than tables, and
-- deliberately. A rollup is scoped to "the last N broadcasts", N is a command-line
-- flag, and a table keyed without N would be quietly wrong the first time anyone
-- passed --stream-count 20. Same division tm.compare_slots() already draws: the
-- per-day buckets are stored, the busiest-window trim is computed at read time.
--
-- The timezone rule from 001_schema.sql applies throughout. Convert the parameters
-- once, into a half-open range of instants, and never put AT TIME ZONE on an
-- indexed column in a WHERE clause.

SET LOCAL search_path = tm, public;


-- --------------------------------------------------------------------------
-- where a broadcast happened
-- --------------------------------------------------------------------------

-- There is no location in the sample stream and there cannot be: neither platform
-- reports one. The only place a park name exists is the title the streamer wrote,
-- so the rule that reads it has to be configuration rather than a guess.
--
-- SUBSTRING and deliberately not a regex. A regex living in a data row is a
-- footgun with a long fuse -- one malformed rule and every refresh from then on
-- raises, in a function nobody is watching. A substring cannot fail.
--
-- `seq` is explicit rather than implied by rule_id so a rule can be slotted
-- BETWEEN two others without renumbering the rest. Lowest matching seq wins, which
-- is what makes 'Magic Kingdom' beatable by a more specific rule placed above it.
CREATE TABLE IF NOT EXISTS tm.stream_location_rule (
    rule_id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id bigint  NOT NULL REFERENCES tm.channel ON DELETE CASCADE,
    seq        integer NOT NULL,
    pattern    text    NOT NULL,
    location   text    NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT stream_location_rule_order UNIQUE (channel_id, seq),
    CONSTRAINT stream_location_rule_pattern  CHECK (btrim(pattern)  <> ''),
    CONSTRAINT stream_location_rule_location CHECK (btrim(location) <> '')
);


-- NULL when nothing matches, and never a fabricated label. The charts render that
-- as "Unknown", which is a reading the streamer can act on -- it says a title has
-- drifted out of its rule -- where inventing a location from the title would not.
CREATE OR REPLACE FUNCTION tm.stream_location(p_channel_id bigint, p_title text)
RETURNS text
LANGUAGE sql STABLE AS $$
    SELECT r.location
      FROM tm.stream_location_rule r
     WHERE r.channel_id = p_channel_id
       AND coalesce(p_title, '') <> ''
       AND strpos(lower(p_title), lower(r.pattern)) > 0
     ORDER BY r.seq
     LIMIT 1;
$$;


-- --------------------------------------------------------------------------
-- one row per broadcast
-- --------------------------------------------------------------------------

-- Wide rather than long, unlike tm.report_stream_metric. That table is the general
-- per-broadcast summary and long format is right for it; this one exists to be
-- drawn, and a chart wants the follower delta and the like peak on the same row as
-- the date and the location.
CREATE TABLE IF NOT EXISTS tm.report_stream_trend (
    channel_id bigint NOT NULL REFERENCES tm.channel ON DELETE CASCADE,
    -- In the key for the reason it is in the other two report tables: local_date
    -- and weekday are both derived from it, so a refresh written under one zone
    -- must be invisible to a read under another.
    tz         text   NOT NULL,
    stream_id  bigint NOT NULL REFERENCES tm.stream ON DELETE CASCADE,
    platform   tm.platform_kind NOT NULL,

    -- The date the broadcast STARTED, not the one its last sample landed on. A
    -- stream that opens at 11pm Sunday and runs to 2am Monday is a Sunday stream,
    -- which is how a person schedules one and how the weekday chart must read it.
    local_date date NOT NULL,
    -- 0 = Monday, matching Python's date.weekday(). PostgreSQL's isodow counts
    -- 1..7 from Monday, so the -1 is the whole of the conversion -- and it is taken
    -- from local_date rather than from the timestamptz so there is exactly one
    -- AT TIME ZONE in the refresh and the two can never disagree.
    weekday    smallint NOT NULL,

    started_at timestamptz(0) NOT NULL,
    ended_at   timestamptz(0),          -- NULL while the broadcast is still live
    title      text,
    location   text,                    -- NULL when no rule matched

    -- Across the broadcast's own samples only, which is what makes it attributable
    -- to this stream and so to this weekday and this park. tm.report_daily_peak
    -- deliberately measures the other thing -- the whole local day, dark rows
    -- included -- because a day's delta must not lose followers gained while off.
    -- Both are true; they answer different questions.
    follower_delta integer,             -- twitch; NULL when never sampled
    likes_peak     integer,             -- youtube; likes only climb, so peak = last
    peak_viewers   integer,
    sample_count   integer NOT NULL,
    computed_at    timestamptz NOT NULL DEFAULT now(),

    PRIMARY KEY (channel_id, tz, stream_id),
    CONSTRAINT report_stream_trend_weekday CHECK (weekday BETWEEN 0 AND 6)
);


-- Ordering is by started_at and never by local_date: two broadcasts share a date,
-- which is the entire reason this axis exists.
CREATE INDEX IF NOT EXISTS report_stream_trend_recent
    ON tm.report_stream_trend (channel_id, tz, platform, started_at DESC);


-- --------------------------------------------------------------------------
-- filling it
-- --------------------------------------------------------------------------

-- MUST run after tm.refresh_stream_metrics(), because it reads what that writes.
--
-- DELETE then INSERT rather than an upsert, for refresh_clock_buckets()' reason:
-- the result set is sparse, and a correction that removes a broadcast has to be
-- able to remove its row rather than leave a stale one standing for ever.
CREATE OR REPLACE FUNCTION tm.refresh_stream_trends(
    p_channel_id bigint,
    p_from       date,
    p_to         date,
    p_tz         text DEFAULT NULL
) RETURNS integer
LANGUAGE plpgsql AS $$
DECLARE
    v_tz   text;
    v_from timestamptz;
    v_to   timestamptz;
    v_rows integer;
BEGIN
    SELECT coalesce(p_tz, c.report_timezone) INTO v_tz
      FROM tm.channel c WHERE c.channel_id = p_channel_id;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'unknown channel_id %', p_channel_id;
    END IF;
    IF p_to < p_from THEN
        RAISE EXCEPTION 'empty range: % .. %', p_from, p_to;
    END IF;

    v_from := (p_from::timestamp)     AT TIME ZONE v_tz;
    v_to   := ((p_to + 1)::timestamp) AT TIME ZONE v_tz;

    -- Matched on the broadcast's sample WINDOW overlapping the range, not on its
    -- start: a stream that began before midnight and ran past it belongs to both
    -- days, and keying off started_at would drop it from the second. Reads
    -- tm.stream rather than scanning tm.sample_all the way refresh_range() does --
    -- a channel has hundreds of streams and millions of samples, and first/last
    -- sample_at are maintained on the stream row precisely so this is cheap.
    DELETE FROM tm.report_stream_trend r
     WHERE r.channel_id = p_channel_id
       AND r.tz = v_tz
       AND r.stream_id IN (
           SELECT s.stream_id
             FROM tm.stream s
             JOIN tm.platform_account a ON a.account_id = s.account_id
            WHERE a.channel_id = p_channel_id
              AND s.first_sample_at <  v_to
              AND s.last_sample_at  >= v_from);

    INSERT INTO tm.report_stream_trend (
        channel_id, tz, stream_id, platform, local_date, weekday,
        started_at, ended_at, title, location,
        follower_delta, likes_peak, peak_viewers, sample_count, computed_at)
    SELECT p_channel_id, v_tz, s.stream_id, a.platform,
           d.local_date,
           (extract(isodow FROM d.local_date)::smallint - 1),
           coalesce(s.started_at, s.first_sample_at),
           s.ended_at, s.title,
           tm.stream_location(p_channel_id, s.title),
           f.delta, l.peak, v.peak,
           s.sample_count, now()
      FROM tm.stream s
      JOIN tm.platform_account a ON a.account_id = s.account_id
      -- One AT TIME ZONE, named once, so local_date and weekday cannot drift.
      CROSS JOIN LATERAL (
          SELECT (coalesce(s.started_at, s.first_sample_at)
                    AT TIME ZONE v_tz)::date AS local_date) d
      LEFT JOIN tm.report_stream_metric f
             ON f.stream_id = s.stream_id AND f.metric = 'followers'
      LEFT JOIN tm.report_stream_metric l
             ON l.stream_id = s.stream_id AND l.metric = 'likes'
      LEFT JOIN tm.report_stream_metric v
             ON v.stream_id = s.stream_id AND v.metric = 'viewers'
     WHERE a.channel_id = p_channel_id
       AND s.first_sample_at <  v_to
       AND s.last_sample_at  >= v_from;

    GET DIAGNOSTICS v_rows = ROW_COUNT;
    RETURN v_rows;
END;
$$;


-- --------------------------------------------------------------------------
-- the entry points, again
-- --------------------------------------------------------------------------
--
-- 005 is applied in production, so these are replacements in a new file rather
-- than edits to it -- the same rule 005 itself was written under. Both bodies are
-- 005's, with one PERFORM appended after the stream metrics they depend on.

CREATE OR REPLACE FUNCTION tm.refresh_range(
    p_channel_id     bigint,
    p_from           date,
    p_to             date,
    p_tz             text    DEFAULT NULL,
    p_bucket_minutes integer DEFAULT 30
) RETURNS void
LANGUAGE plpgsql AS $$
DECLARE
    v_platform tm.platform_kind;
    v_tz       text;
    v_from     timestamptz;
    v_to       timestamptz;
    v_stream   bigint;
BEGIN
    SELECT coalesce(p_tz, c.report_timezone) INTO v_tz
      FROM tm.channel c WHERE c.channel_id = p_channel_id;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'unknown channel_id %', p_channel_id;
    END IF;

    FOR v_platform IN
        SELECT platform FROM tm.platform_account WHERE channel_id = p_channel_id
    LOOP
        PERFORM tm.refresh_daily_peaks(p_channel_id, v_platform, p_from, p_to, v_tz);
        PERFORM tm.refresh_clock_buckets(p_channel_id, v_platform, p_from, p_to,
                                         p_bucket_minutes, v_tz);
    END LOOP;

    v_from := (p_from::timestamp)     AT TIME ZONE v_tz;
    v_to   := ((p_to + 1)::timestamp) AT TIME ZONE v_tz;

    FOR v_stream IN
        SELECT DISTINCT s.stream_id
          FROM tm.sample_all s
         WHERE s.channel_id = p_channel_id
           AND s.stream_id IS NOT NULL
           AND s.sampled_at >= v_from AND s.sampled_at < v_to
    LOOP
        PERFORM tm.refresh_stream_metrics(v_stream);
    END LOOP;

    -- Last, and not inside the loop above: it reads every row those calls wrote.
    PERFORM tm.refresh_stream_trends(p_channel_id, p_from, p_to, v_tz);
END;
$$;


CREATE OR REPLACE FUNCTION tm.refresh_after_sample(
    p_account_id     bigint,
    p_sampled_at     timestamptz,
    p_bucket_minutes integer DEFAULT 30,
    p_stream_id      bigint  DEFAULT NULL
) RETURNS void
LANGUAGE plpgsql AS $$
DECLARE
    v_channel bigint;
    v_tz      text;
    v_day     date;
    -- A loop variable of its own, so v_day still means "the sample's day" after
    -- the loop rather than whatever the last iteration left in it.
    v_loop    date;
BEGIN
    SELECT a.channel_id, c.report_timezone INTO v_channel, v_tz
      FROM tm.platform_account a JOIN tm.channel c USING (channel_id)
     WHERE a.account_id = p_account_id;
    IF v_channel IS NULL THEN
        RETURN;
    END IF;

    v_day := (p_sampled_at AT TIME ZONE v_tz)::date;
    FOR v_loop IN SELECT unnest(ARRAY[v_day - 1, v_day]) LOOP
        PERFORM tm.refresh_daily_peaks(v_channel, a.platform, v_loop, v_loop, v_tz)
           FROM tm.platform_account a WHERE a.channel_id = v_channel;
        PERFORM tm.refresh_clock_buckets(v_channel, a.platform, v_loop, v_loop,
                                         p_bucket_minutes, v_tz)
           FROM tm.platform_account a WHERE a.channel_id = v_channel;
    END LOOP;

    IF p_stream_id IS NOT NULL THEN
        PERFORM tm.refresh_stream_metrics(p_stream_id);
    END IF;

    -- Two days here as well, and for refresh_after_sample()'s own reason: a
    -- broadcast that straddles local midnight is still being written to while
    -- yesterday's row exists, and its ended_at and follower delta both move.
    PERFORM tm.refresh_stream_trends(v_channel, v_day - 1, v_day, v_tz);
END;
$$;


-- --------------------------------------------------------------------------
-- reads, for the site generator
-- --------------------------------------------------------------------------

-- store.stream_trends(): the last p_streams broadcasts, OLDEST FIRST.
--
-- Bounded by p_lookback days for the reason trends.LOOKBACK_DAYS exists: a channel
-- dormant since last year must not drag its whole history into every run. The
-- predicate is local_date > p_end_day - p_lookback, which is p_lookback days
-- inclusive -- exactly trends.streamed_window()'s
-- earliest = end_day - (lookback - 1).
--
-- Coming up short is not a failure. The chart simply has fewer bars.
CREATE OR REPLACE FUNCTION tm.stream_trends(
    p_channel_id bigint,
    p_platform   tm.platform_kind,
    p_end_day    date,
    p_streams    integer DEFAULT 10,
    p_lookback   integer DEFAULT 90,
    p_tz         text    DEFAULT NULL
) RETURNS TABLE (stream_id bigint, local_date date, started_at timestamptz,
                 weekday smallint, title text, location text,
                 follower_delta integer, likes_peak integer, peak_viewers integer)
LANGUAGE sql STABLE AS $$
    WITH zone AS (
        SELECT coalesce(p_tz, c.report_timezone) AS name
          FROM tm.channel c WHERE c.channel_id = p_channel_id),
    picked AS (
        SELECT r.stream_id, r.local_date, r.started_at, r.weekday, r.title,
               r.location, r.follower_delta, r.likes_peak, r.peak_viewers
          FROM tm.report_stream_trend r CROSS JOIN zone z
         WHERE r.channel_id = p_channel_id
           AND r.platform   = p_platform
           AND r.tz         = z.name
           AND r.local_date <= p_end_day
           AND r.local_date >  p_end_day - greatest(1, p_lookback)
         ORDER BY r.started_at DESC
         LIMIT greatest(0, p_streams))
    SELECT p.stream_id, p.local_date, p.started_at, p.weekday, p.title,
           p.location, p.follower_delta, p.likes_peak, p.peak_viewers
      FROM picked p
     ORDER BY p.started_at;
$$;


-- store.stream_groups(): the same broadcasts, rolled up by weekday or by location.
--
-- Built ON TOP of tm.stream_trends() rather than beside it, so the two charts can
-- never describe different windows -- the bar chart and the rollup under it always
-- summarise the identical set of broadcasts.
--
-- SPARSE, like tm.compare_slots(): a weekday nobody streamed on has no row. The
-- caller builds the Mon..Sun axis and this fills it, for the same reason -- a
-- renderer that took its axis from the rows would silently relabel itself.
--
-- An unmatched location comes back as '' rather than NULL, so group_key is always
-- groupable and the caller has one thing to translate into "Unknown".
CREATE OR REPLACE FUNCTION tm.stream_groups(
    p_channel_id bigint,
    p_platform   tm.platform_kind,
    p_metric     tm.metric_kind,
    p_grouping   text,
    p_end_day    date,
    p_streams    integer DEFAULT 10,
    p_lookback   integer DEFAULT 90,
    p_tz         text    DEFAULT NULL
) RETURNS TABLE (group_key text, streams integer, total bigint,
                 average numeric, best integer, best_stream_id bigint)
LANGUAGE plpgsql STABLE AS $$
BEGIN
    IF p_grouping NOT IN ('weekday', 'location') THEN
        RAISE EXCEPTION 'unknown grouping %; expected weekday or location',
                        p_grouping;
    END IF;
    -- The wide table carries two metrics and no more. Raising beats returning
    -- nothing, which would read as "this channel gained no subscribers".
    IF p_metric NOT IN ('followers', 'likes') THEN
        RAISE EXCEPTION 'unsupported metric %; expected followers or likes',
                        p_metric;
    END IF;

    RETURN QUERY
    WITH picked AS (
        SELECT t.stream_id, t.weekday, t.location,
               CASE p_metric WHEN 'followers' THEN t.follower_delta
                             WHEN 'likes'     THEN t.likes_peak END AS value
          FROM tm.stream_trends(p_channel_id, p_platform, p_end_day,
                                p_streams, p_lookback, p_tz) t),
    -- A broadcast the metric was never sampled on is dropped rather than counted
    -- as a zero: it would drag every average it touched towards nothing and the
    -- chart would say the day was bad when the poller was.
    keyed AS (
        SELECT CASE p_grouping WHEN 'weekday' THEN k.weekday::text
                               ELSE coalesce(k.location, '') END AS gkey,
               k.stream_id, k.value
          FROM picked k
         WHERE k.value IS NOT NULL),
    -- Earliest stream wins a tie, the tie-break every other report function uses.
    best AS (
        SELECT DISTINCT ON (b.gkey) b.gkey, b.stream_id, b.value
          FROM keyed b
         ORDER BY b.gkey, b.value DESC, b.stream_id ASC)
    SELECT g.gkey, count(*)::integer, sum(g.value)::bigint,
           avg(g.value)::numeric(18,6), x.value, x.stream_id
      FROM keyed g JOIN best x ON x.gkey = g.gkey
     GROUP BY g.gkey, x.value, x.stream_id
     ORDER BY g.gkey;
END;
$$;


-- --------------------------------------------------------------------------
-- the one-time backfill
-- --------------------------------------------------------------------------
--
-- tm.report_stream_metric is empty on every database that predates this file, and
-- not because nothing had got to it: the function that fills it raised on every
-- call until 006 corrected it, and 006 replaced the function without rebuilding
-- what the broken one never wrote. tm.report_stream_trend reads that table, so
-- without this it would fill with NULLs and the charts would stay blank.
--
-- Nothing else would notice. store.ensure_reports() judges coverage against
-- tm.report_daily_peak, which is complete -- so it would report the window healthy
-- and refresh only its tail, for ever.
--
-- One pass of tm.refresh_range() over each channel's whole span fills both, which
-- is exactly what db_cmd._rebuild_reports() already does after `db --import`.
DO $backfill$
DECLARE
    v_span record;
BEGIN
    FOR v_span IN
        SELECT s.channel_id,
               min(s.sampled_at AT TIME ZONE c.report_timezone)::date AS first_day,
               max(s.sampled_at AT TIME ZONE c.report_timezone)::date AS last_day
          FROM tm.sample_all s
          JOIN tm.channel c ON c.channel_id = s.channel_id
         GROUP BY s.channel_id
    LOOP
        PERFORM tm.refresh_range(v_span.channel_id, v_span.first_day,
                                 v_span.last_day, NULL, 30);
    END LOOP;
END;
$backfill$;
