-- Where a broadcast sits in its category directory, sampled on its own cadence.
--
-- The question is the one a streamer actually asks: how far down
-- twitch.tv/directory/category/irl do I have to scroll to find myself? Helix
-- answers it without scraping anything -- GET /helix/streams?game_id=... returns
-- the category already sorted by viewer_count DESC, which is the ordering the
-- directory page shows under "Sort by: Viewers (High to Low)". Walking the
-- cursor to the end of IRL is 7 requests and 1.3 seconds against a budget of 800
-- requests per minute, so a ten-minute pass costs about a tenth of one percent
-- of one minute's allowance. There is nothing to rate-limit here.
--
-- WHY THIS IS NOT A `position` COLUMN, which is the first thing a reader will
-- want to simplify it into.
--
-- Viewer counts in the tail of a category are massively tied. Measured on IRL:
-- 532 live streams, of which 207 had exactly 1 viewer and 29 had 0. So a
-- one-viewer stream's index in that list is not a fact about the stream, it is
-- whatever order Helix happened to emit the tie block in -- anywhere from 295 to
-- 501. Two passes taken seconds apart moved 486 of 488 streams, 31 of them by
-- more than twenty places, with nothing whatsoever having changed.
--
-- What IS stable is the count of streams strictly ahead. So that is the number
-- stored, and the two ranks are generated from it:
--
--     streams_ahead   how many streams had MORE viewers        (stable)
--     tie_count       how many shared this viewer count, self included
--     rank_best       streams_ahead + 1        -- top of the tie block
--     rank_worst      streams_ahead + tie_count -- bottom of it
--
-- Storing only rank_best would not be wrong, it would be rhetorical: it reads
-- "#295 of 532" for a channel that could equally honestly be called #501. Both
-- bounds, and tie_count beside them, is the whole answer -- and a reader can see
-- from tie_count alone how much the interval is worth.
--
-- WHY NOT COLUMNS ON tm.twitch_sample. 008 put watch time on an existing table
-- precisely because the grain already had a row, so the question is fair. Four
-- reasons it does not apply:
--
--   * The cadences differ -- 60s for samples, 600s for a directory pass -- so
--     nine rows in ten would carry NULL rank, in the widest table here.
--   * The instants would not coincide anyway. record_twitch_sample keys on the
--     exact second, and a pass that starts at 12:00:03 is not the sample at
--     12:00:00. Joining them would need a nearest-neighbour match, which is the
--     kind of fabrication 007 refuses for locations.
--   * tm.twitch_sample is the CSV's shape. New columns there mean a new
--     METRICS_HEADER entry and storage._widen() rewriting every archive on disk.
--   * The viewer_count below is a DIFFERENT measurement from the sample's: it is
--     what the LISTING said while it was being counted, not what
--     /streams?user_login= said at the minute tick. Both are true; they answer
--     different questions, and keeping the listing's figure beside the rank it
--     produced is what lets a later reader check the arithmetic.
--
-- There is no backfill block in this file, and the next reader should not go
-- looking for the one 007 and 008 both needed. Those files added columns over
-- history that nothing would ever fill. These rows have no history: the first
-- one is written by the first pass.
--
-- The timezone rule from 001_schema.sql applies as everywhere else. Nothing here
-- is keyed on a local date, so it barely arises -- but note that sampled_at is
-- the instant the pass STARTED, before page one.

SET LOCAL search_path = tm, public;


-- --------------------------------------------------------------------------
-- one pass, one channel
-- --------------------------------------------------------------------------

-- Keyed on the tick, like the sample tables, and attributed to a broadcast,
-- unlike them.
--
-- Both, and for two different reasons. UNIQUE (account_id, sampled_at) is the
-- idempotence key: the grain of the measurement is a tick, so a re-run that
-- lands on the same second must be a no-op rather than a duplicate. stream_id is
-- the attribution: every venue-shaped read on this site reaches a location by
-- way of tm.report_stream_trend, which is keyed on stream_id and gets its
-- location from tm.stream_location(channel_id, title). Without stream_id here,
-- "average rank at Hollywood Studios" would have to re-derive the broadcast by
-- interval-containment against first_sample_at/last_sample_at -- and a rank
-- taken in the gap between two broadcasts would land in neither or in both.
CREATE TABLE IF NOT EXISTS tm.directory_rank (
    rank_id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id  bigint NOT NULL,
    account_id  bigint NOT NULL,
    -- Second precision, matching tm.twitch_sample: whole seconds are all
    -- storage.utc_stamp() has ever written, so the unique constraint below means
    -- exactly what one tick meant and a stray microsecond cannot invent a
    -- second pass.
    --
    -- The instant the pass STARTED. Every channel ranked from the same walk of
    -- the same category shares this value, which is what makes "who was higher
    -- at 14:20" a question with an answer.
    sampled_at  timestamptz(0) NOT NULL,
    -- NOT NULL, deliberately unlike tm.twitch_sample.stream_id. There, NULL is
    -- the liveness flag, and offline rows have to exist because follower counts
    -- keep moving while a channel is dark. A rank has no offline meaning at all
    -- -- a channel that is not streaming is not in the directory -- so making
    -- "a rank belongs to a broadcast" structural is both honest and what the
    -- venue rollups need. "The channel was dark" is already recorded, by
    -- tm.twitch_sample.stream_id IS NULL and by report_daily_peak.status.
    stream_id   bigint NOT NULL REFERENCES tm.stream ON DELETE RESTRICT,

    -- The INPUT to the measurement, stored beside its result -- the same rule
    -- 009 follows by putting tz in its primary key. game_id is what was actually
    -- paged; it is not a copy of a lookup, it is the parameter that produced
    -- these numbers.
    --
    -- game_name is denormalised on purpose, and it is a point-in-time
    -- observation rather than a key -- the same treatment tm.stream.game gets.
    -- A tm.category table with a mutable name would be worse than this: when
    -- Twitch renames a category, every chart of last year would silently
    -- relabel itself. Grouping by game_id keeps a series continuous across a
    -- rename; keeping the observed name keeps each era's label true.
    game_id     text NOT NULL,
    game_name   text,

    -- NULL means the channel's own row was not in the listing. The directory is
    -- eventually consistent and this genuinely happens, so it gets NULL rather
    -- than a guess -- tm.stream_location's rule -- and both generated ranks
    -- follow it to NULL for nothing. A row is still written, because that is
    -- what makes "how often is the directory inconsistent" a countable thing;
    -- writing no row would be indistinguishable from a missed tick, which is
    -- the same distinction 001 insists on between a dark day and a silent one.
    streams_ahead integer,
    -- INCLUDING this stream, so 1 means "no tie". Any other definition makes
    -- rank_worst's arithmetic wrong.
    tie_count     integer,
    -- As the LISTING reported it. See the header: not the sample's figure.
    viewer_count  integer,
    -- Rows actually read. Never NULL and never 0 -- see directory_rank_nonempty.
    total_streams integer NOT NULL,

    -- How the pass went, stored as facts rather than as a verdict.
    --
    -- A single `truncated` boolean would be too coarse, because truncation does
    -- not damage the four numbers equally. The listing is sorted DESC, so if the
    -- channel's own row was found on page k, then every stream ahead of it was
    -- on pages 1..k -- which means streams_ahead, and therefore rank_best, are
    -- EXACT even on a pass that was cut short. Only tie_count and total_streams
    -- degrade, into lower bounds. Throwing away an exact rank because the walk
    -- stopped later would discard the expensive half of the measurement.
    --
    -- So: pages_read and page_cap are raw facts, listing_complete says the
    -- cursor ran out before the cap, and the interesting verdict is derived --
    -- `pages_read < page_cap AND NOT listing_complete` is a pass abandoned by
    -- something other than the cap.
    pages_read   smallint NOT NULL,
    page_cap     smallint NOT NULL,
    -- How long the walk took, which is the rank analogue of 008's
    -- covered_seconds: it says how much smearing is inside one measurement. IRL
    -- is 1.3 seconds, but Just Chatting is 66 pages and 17.7, so the tail of
    -- that list is seventeen seconds staler than its head -- in a category where
    -- 486 of 488 streams moved between two back-to-back passes.
    pass_seconds integer NOT NULL,
    -- Knowable only at write time and recomputable from nothing afterwards, so
    -- it is stored: total_streams and tie_count are EXACT when this is true and
    -- LOWER BOUNDS when it is false.
    listing_complete boolean NOT NULL,
    ingest_source text NOT NULL DEFAULT 'ranker',

    -- The invariants made structural instead of merely observed, the same
    -- argument is_live makes on tm.twitch_sample. Integer addition is IMMUTABLE,
    -- so both are legal STORED and both can be indexed -- and a future writer
    -- cannot produce a row whose rank disagrees with its streams_ahead.
    rank_best  integer GENERATED ALWAYS AS (streams_ahead + 1) STORED,
    rank_worst integer GENERATED ALWAYS AS (streams_ahead + tie_count) STORED,

    -- The denormalised channel_id and the composite FK that stops it drifting,
    -- the same pair tm.twitch_sample carries. Unlike there it is a convenience
    -- rather than load-bearing -- stream_id is NOT NULL, so a path to the
    -- channel exists either way -- and it is here because every report read
    -- filters by channel and would otherwise take two hops to get one.
    CONSTRAINT directory_rank_account_fk FOREIGN KEY (account_id, channel_id)
        REFERENCES tm.platform_account (account_id, channel_id) ON DELETE RESTRICT,
    -- What makes a re-run idempotent rather than duplicating: a --once pass
    -- beside the timer can land on the same second.
    CONSTRAINT directory_rank_once UNIQUE (account_id, sampled_at),
    CONSTRAINT directory_rank_game CHECK (btrim(game_id) <> ''),
    -- An empty listing cannot have contained a channel that was live in it, so
    -- such a row would be a fabrication rather than an edge case. 009's rule: a
    -- row that exists always says something.
    CONSTRAINT directory_rank_nonempty CHECK (total_streams >= 1),
    -- Either the channel was found in its own category and all three of these
    -- are known, or it was not and none of them are. Half a position would
    -- reach a chart as a blank bar with a filled tooltip -- the pairing rule
    -- report_daily_peak and report_location_watch both already enforce.
    CONSTRAINT directory_rank_self_triple CHECK (
        (streams_ahead IS NULL) = (tie_count IS NULL)
        AND (streams_ahead IS NULL) = (viewer_count IS NULL)),
    -- "The channel and everyone tied with it fit inside the listing." Stated
    -- this way rather than as streams_ahead < total_streams because this is what
    -- makes rank_worst <= total_streams true, it degrades correctly at the very
    -- top (0 + 1 <= 1 passes), and it stays true under truncation: tie_count
    -- counts only ties SEEN and total_streams counts rows READ, so both are
    -- drawn from the same pages.
    CONSTRAINT directory_rank_bounds CHECK (
        streams_ahead IS NULL
        OR (streams_ahead >= 0 AND tie_count >= 1 AND viewer_count >= 0
            AND streams_ahead + tie_count <= total_streams)),
    CONSTRAINT directory_rank_pages CHECK (
        pages_read BETWEEN 1 AND page_cap AND pass_seconds >= 0)
);

-- Per-broadcast reads, which is the shape a future venue rollup scans in.
CREATE INDEX IF NOT EXISTS directory_rank_stream
    ON tm.directory_rank (stream_id, sampled_at);
-- "How big was this category over time" -- a question about the directory
-- rather than about us, and nothing else here can answer it.
CREATE INDEX IF NOT EXISTS directory_rank_category
    ON tm.directory_rank (game_id, sampled_at);
-- Deliberately NOT created: anything on (account_id, sampled_at). The unique
-- constraint above already is an index, exactly as 001 notes for the samples.


-- --------------------------------------------------------------------------
-- the write path
-- --------------------------------------------------------------------------

-- Returns the rank_id, or NULL when there is no broadcast to hang the rank on.
--
-- Opening and closing broadcasts stays the poller's job, and this function
-- deliberately does not call tm.open_or_touch_stream: two writers racing to open
-- a stream would fight the stream_open_one_per_account partial unique index, and
-- the ranker has no business deciding when a broadcast began. So it LOOKS the
-- stream up, on the (account_id, platform_stream_id) unique key, and returns
-- NULL if the poller has not recorded that broadcast yet. The caller logs it and
-- skips the tick; the next pass ten minutes later will find it.
--
-- Looking up by platform_stream_id rather than "the currently open stream" is
-- what makes a late write attach to the broadcast it actually measured, instead
-- of to whichever one happens to be open now.
CREATE OR REPLACE FUNCTION tm.record_directory_rank(
    p_account_id         bigint,
    p_sampled_at         timestamptz,
    p_platform_stream_id text,
    p_game_id            text,
    p_total_streams      integer,
    p_pages_read         integer,
    p_page_cap           integer,
    p_pass_seconds       integer,
    p_listing_complete   boolean,
    p_game_name          text    DEFAULT NULL,
    p_streams_ahead      integer DEFAULT NULL,   -- NULL: not in its own listing
    p_tie_count          integer DEFAULT NULL,
    p_viewer_count       integer DEFAULT NULL,
    p_source             text    DEFAULT 'ranker'
) RETURNS bigint
LANGUAGE plpgsql AS $$
DECLARE
    v_channel_id bigint;
    v_stream_id  bigint;
    v_rank_id    bigint;
BEGIN
    SELECT channel_id INTO v_channel_id
      FROM tm.platform_account WHERE account_id = p_account_id;
    IF v_channel_id IS NULL THEN
        RAISE EXCEPTION 'unknown account_id %', p_account_id;
    END IF;

    SELECT stream_id INTO v_stream_id
      FROM tm.stream
     WHERE account_id = p_account_id
       AND platform_stream_id = nullif(p_platform_stream_id, '');
    IF v_stream_id IS NULL THEN
        RETURN NULL;   -- the poller has not seen this broadcast yet
    END IF;

    INSERT INTO tm.directory_rank AS d (
        channel_id, account_id, sampled_at, stream_id,
        game_id, game_name, streams_ahead, tie_count, viewer_count,
        total_streams, pages_read, page_cap, pass_seconds, listing_complete,
        ingest_source)
    VALUES (v_channel_id, p_account_id, p_sampled_at, v_stream_id,
            p_game_id, p_game_name, p_streams_ahead, p_tie_count, p_viewer_count,
            p_total_streams, p_pages_read, p_page_cap, p_pass_seconds,
            p_listing_complete, p_source)
    -- Complete beats incomplete, and nothing else is ever overwritten.
    --
    -- Deliberately NOT the coalescing merge record_twitch_sample uses. That one
    -- exists because three writers can arrive at the same (account, second) each
    -- knowing something the others do not. Here there is only ever one writer
    -- per pass, and a blind merge would let a truncated pass replace a complete
    -- pass's exact total_streams with a lower bound.
    ON CONFLICT (account_id, sampled_at) DO UPDATE SET
        game_id       = EXCLUDED.game_id,
        game_name     = EXCLUDED.game_name,
        streams_ahead = EXCLUDED.streams_ahead,
        tie_count     = EXCLUDED.tie_count,
        viewer_count  = EXCLUDED.viewer_count,
        total_streams = EXCLUDED.total_streams,
        pages_read    = EXCLUDED.pages_read,
        pass_seconds  = EXCLUDED.pass_seconds,
        listing_complete = true
      WHERE EXCLUDED.listing_complete AND NOT d.listing_complete
    RETURNING d.rank_id INTO v_rank_id;

    -- The conflict path declined to update, because what is already stored for
    -- this tick is at least as good. That is a success and not a failure, so it
    -- returns the row that IS stored -- which keeps NULL meaning exactly one
    -- thing to the caller: there was no broadcast to attach a rank to.
    IF v_rank_id IS NULL THEN
        SELECT rank_id INTO v_rank_id
          FROM tm.directory_rank
         WHERE account_id = p_account_id AND sampled_at = p_sampled_at;
    END IF;

    RETURN v_rank_id;
END;
$$;


-- --------------------------------------------------------------------------
-- reading it back
-- --------------------------------------------------------------------------

-- The most recent pass per channel, which is what a status line wants.
--
-- midrank is the single number for a chart that has room for one line: the
-- middle of the tie block rather than either edge. Converted here rather than in
-- a renderer for the reason 008 converts minutes to hours in SQL -- one place
-- beats every caller remembering to.
CREATE OR REPLACE FUNCTION tm.latest_directory_rank(p_channel_id bigint)
RETURNS TABLE (sampled_at timestamptz, game_id text, game_name text,
               viewer_count integer, rank_best integer, rank_worst integer,
               midrank numeric, tie_count integer, total_streams integer,
               listing_complete boolean)
LANGUAGE sql STABLE AS $$
    SELECT DISTINCT ON (d.account_id)
           d.sampled_at, d.game_id, d.game_name, d.viewer_count,
           d.rank_best, d.rank_worst,
           d.streams_ahead + (d.tie_count + 1) / 2.0,
           d.tie_count, d.total_streams, d.listing_complete
      FROM tm.directory_rank d
     WHERE d.channel_id = p_channel_id
     ORDER BY d.account_id, d.sampled_at DESC;
$$;


-- Every category this channel has been ranked in, last observed name winning --
-- a read function rather than a table, so there is no stored name for a Twitch
-- rename to silently rewrite and nothing new for ensure_reports() to be blind
-- to.
CREATE OR REPLACE FUNCTION tm.categories_ranked(p_channel_id bigint)
RETURNS TABLE (game_id text, game_name text, passes bigint,
               first_seen timestamptz, last_seen timestamptz)
LANGUAGE sql STABLE AS $$
    SELECT DISTINCT ON (d.game_id)
           d.game_id, d.game_name,
           count(*)        OVER (PARTITION BY d.game_id),
           min(d.sampled_at) OVER (PARTITION BY d.game_id),
           max(d.sampled_at) OVER (PARTITION BY d.game_id)
      FROM tm.directory_rank d
     WHERE d.channel_id = p_channel_id
     ORDER BY d.game_id, d.sampled_at DESC;
$$;
